# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

def shared_pods
    pod 'Alamofire', '~> 4.0.1'
    pod 'PopupDialog', '~> 0.5'
end

target 'Autonome' do
    shared_pods
end


